### ISSUE TITLE
remove clippy

### ISSUE THREAD

**Issue by michaelficarra** [rixth/jsbeautify-for-chrome#1]
It's obvious copyright infringement (unless you have consent from Microsoft, which I don't see included in the repo), and you don't want those asshats coming after you for something so stupid.

Also, clippy is really stupid.

**Comment by rixth** [comment]
As for him being stupid, that's why I'm offering the two packaged versions.

With respect to my use of Clippy, I think it's fair use. I've noted this, and that Microsoft owns the copyright in the license file. If they want to take the time to spend a DMCA notice, they're welcome to.

**Comment by rixth** [comment]
Also: version with clippy has 44% more downloads than the version without =)
