### ISSUE TITLE
Chrome dev getting "pretty print"

### ISSUE THREAD

**Issue by feelepxyz** [rixth/jsbeautify-for-chrome#2]
Hey! 

Seems this feature is creeping its way into the chrome dev tools.. exists in chrome dev 12. And slightly modified with it's own button in chrome 13 canary. 

However, their implementation seems kind of crappy atm! 

Cheers

**Comment by rixth** [comment]
Heh indeed. I was actually talking to Paul Irish (the lead developer on the dev tools) about this at JSConf a couple days ago.
