### ISSUE TITLE
Js beautifier breaks on long inputs.

### ISSUE THREAD

**Issue by shalecraig** [rixth/jsbeautify-for-chrome#3]
Beautification doesn't work on abnormally large inputs.

Example:
1. Load facebook.
2. Open up any of their included js files.
3. Beautify.
4. Scroll to the bottom. The indentation doesn't match, and sometimes it doesn't even match brackets correctly.

Sorry to report this issue, but it's killing it for me. I'm not trying to de-compile facebook's code, but it's an easy example.

**Comment by rixth** [comment]
All the beautifying is powered by a 3rd party lib, https://github.com/einars/js-beautify .

Can you try pasting the source in at jsbeautifier.org and see if you see the same issue?  If you do, I suggest filing a bug on the above repository.

**Comment by shalecraig** [comment]
Yes, it fails there too, thanks for the response.

On 2011-09-14, at 10:12, Tom Rix
reply@reply.github.com
wrote:
