### ISSUE TITLE
Package is 'invalid': Error while installing.

### ISSUE THREAD

**Issue by karimsa** [rixth/jsbeautify-for-chrome#4]
Hey, there!

I tried to install this via the Chrome Web Store (using [this](https://chrome.google.com/extensions/detail/kkioiolcacgoihiiekambdciinadbpfk) link in the [README](https://github.com/rixth/jsbeautify-for-chrome/blob/master/README.md)) and was given the error: `Package is invalid. Details: 'Could not load background script 'javascripts/background.js'.'`

I'm not sure if this is just something wrong with my computer, or if there's a bug in the package.

**_Operating System**_
`Windows 7 Ultimate N (x64)`
**_Browser (UA-String)**_
`Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17`

**Comment by rixth** [comment]
Well, that was embarrassing. I committed [a fix](https://github.com/rixth/jsbeautify-for-chrome/commit/77c0de0ade8a5f22723721e449b3867560416863), tagged [v1.0.2](https://github.com/rixth/jsbeautify-for-chrome/tree/v1.0.2) and uploaded it to the Chrome Web Store.

Thanks for the report!
